"""What to break, and what to call it.

Each entry is (file under server/, what the break means, exact text, replacement).
The text is matched exactly and must appear exactly once — see the mutation traps
in AGENTS.md for every way that goes wrong quietly.
"""

MUTATIONS = [
    ("keys.go", "HEAD sends the value anyway",
     "\tif r.Method == http.MethodHead {", "\tif false {"),
    ("keys.go", "a declared oversize body is read before it is refused",
     "\tif r.ContentLength > s.opts.MaxValue {", "\tif false {"),
    ("keys.go", "the expiry header is stored as an ordinary write",
     "\tif expires.IsZero() {", "\tif true {"),
    ("keys.go", "an unparseable expiry header is ignored",
     '\t\treturn time.Time{}, badRequest("%s must be an RFC 3339 time", headerExpires)',
     "\t\treturn time.Time{}, nil"),
    ("keys.go", "no Content-Length on a value",
     '\tw.Header().Set("Content-Length", strconv.Itoa(len(value)))', "\t_ = strconv.Itoa"),
    ("keys.go", "a delete of a missing key is a 404",
     "\tw.WriteHeader(s.wrote(w, r))\n}\n\n// expiryOf",
     "\tw.WriteHeader(http.StatusNotFound)\n}\n\n// expiryOf"),
    ("errors.go", "a deleted key is not a 404",
     "\t\terrors.Is(err, litekv.ErrorKeyDeleted),\n", ""),
    ("errors.go", "an expired key is not a 404",
     "\t\terrors.Is(err, litekv.ErrorKeyExpired):", "\t\tfalse:"),
    ("errors.go", "a fenced store answers without its term",
     "\tif errors.Is(err, litekv.ErrorFenced) {", "\tif false {"),
    ("errors.go", "a 500 says nothing at all",
     '\t\tmessage = "internal error"', "\t\t_ = message"),
    ("errors.go", "a 500 tells the client what went wrong",
     '\t\tmessage = "internal error"', "\t\tmessage = err.Error()"),
    ("errors.go", "a body over the limit is a 500",
     "\tif errors.As(err, &tooBig) {", "\tif false && errors.As(err, &tooBig) {"),
    ("errors.go", "a closed store is a 500",
     "\tcase errors.Is(err, litekv.ErrorClosed):", "\tcase false:"),
    ("server.go", "MaxValue keeps whatever it was given",
     "\tif opts.MaxValue <= 0 {", "\tif false {"),
    ("server.go", "the queue is not in the write path",
     "\t\twrites:    writer,", "\t\twrites:    db,"),
    ("server.go", "Close leaves the writer running",
     "\treturn s.writer.Close()", "\treturn nil"),
    ("server.go", "the Queue option is dropped on the floor",
     "litekv.WriterOptions{Queue: opts.Queue}", "litekv.WriterOptions{}"),
    ("keys.go", "a delete goes round the queue",
     "\tif err := s.writes.Delete(", "\tif err := s.db.Delete("),
    ("keys.go", "a write goes round the queue",
     "\t\terr = s.writes.Write(key, value)", "\t\terr = s.db.Write(key, value)"),
    # --- replication over the wire -----------------------------------------
    ("replica.go", "a leader hangs up on a diverged follower instead of snapshotting",
     "\t\tif !errors.Is(err, litekv.ErrorDiverged) {", "\t\tif true {"),
    ("replica.go", "the snapshot's hold is released before Follow takes its own",
     "\t\t_, err := s.db.Follow(from, holding, send, until, litekv.ReplicaOptions{})",
     "\t\tif holding != nil {\n\t\t\tholding()\n\t\t}\n\t\t_, err := s.db.Follow(from, nil, send, until, litekv.ReplicaOptions{})"),
    ("replica.go", "a frame's claimed length is not bounded",
     "\tif most < 0 || length > uint64(most) || length > math.MaxInt64 {", "\tif length > math.MaxInt64 {"),
    ("replica.go", "the payload is allocated at the length claimed",
     "\tpayload := make([]byte, 0, min(length, chunk))",
     "\tpayload := make([]byte, 0, length)"),
    ("replica.go", "a short payload is taken as a whole frame",
     "\t\t\treturn nil, err\n\t\t}\n\t\tpayload = payload[:len(payload)+room]",
     "\t\t\treturn payload, nil\n\t\t}\n\t\tpayload = payload[:len(payload)+room]"),
    ("replica.go", "the frames are not flushed as they are cut",
     "\tif err := writeFrame(o.w, kind, at, payload); err != nil {\n\t\treturn err\n\t}\n\to.flusher.Flush()",
     "\tif err := writeFrame(o.w, kind, at, payload); err != nil {\n\t\treturn err\n\t}"),
    ("replica.go", "a snapshot frame goes out as a batch",
     "\t\t\terr := out.frameFrom(frameSnapshot, from, size, snapshot)",
     "\t\t\terr := out.frameFrom(frameBatch, from, size, snapshot)"),
    ("replica.go", "the position the batch leads to is not sent with it",
     "\t\treturn out.frame(frameBatch, next, batch)",
     "\t\treturn out.frame(frameBatch, litekv.DBPosition{}, batch)"),
    ("replica.go", "a from that is not a position is believed",
     "\t\treturn litekv.DBPosition{}, fmt.Errorf(\"%w: %s\", errBadPosition, err)\n\t}\n\n\tvar pos litekv.DBPosition",
     "\t\treturn litekv.DBPosition{}, nil\n\t}\n\n\tvar pos litekv.DBPosition"),
    ("replica.go", "a position is padded base64 rather than raw",
     "\treturn base64.RawURLEncoding.EncodeToString(encoded), nil",
     "\treturn base64.URLEncoding.EncodeToString(encoded), nil"),
    ("replica.go", "a stream is handed out after the streams are closed",
     "\tcase <-s.streams:\n\t\t// A server on its way down.", "\tcase <-make(chan struct{}):\n\t\t// A server on its way down."),
    ("replica.go", "the stream ignores the streams being closed",
     "\t\tcase <-s.streams:\n\t\tcase <-broken:", "\t\tcase <-broken:"),
    ("replica.go", "a follower carrying a newer term does not fence the leader",
     "\tif from.Term > s.db.Term() {", "\tif false {"),
    ("replica.go", "the leader hears the newer term but does not write it down",
     "\t\tif _, noted := s.db.Since(from, io.Discard, litekv.ReplicaOptions{}); noted != nil {",
     "\t\tif _, noted := error(nil), error(nil); noted != nil {"),
    ("follower.go", "a follower asks from nowhere rather than from where it is",
     "\tat, err := positionParam(f.db.Applied())", "\tat, err := positionParam(litekv.DBPosition{})"),
    ("follower.go", "a follower applies a batch from wherever the leader said",
     "\t\t\tfrom := f.db.Applied()", "\t\t\tfrom := next"),
    ("follower.go", "a snapshot is applied as a batch",
     "\t\tcase frameSnapshot:", "\t\tcase frameBatch + 1:"),
    ("follower.go", "a follower gives up when the connection ends",
     "\t\tselect {\n\t\tcase <-ctx.Done():\n\t\t\treturn\n\t\tcase <-time.After(delay):\n\t\t}",
     "\t\t_ = delay\n\t\treturn"),
    ("follower.go", "a refusal is retried as fast as an ordinary disconnection",
     "\t\tcase hopeless(err):\n\t\t\twait = f.opts.MaxBackoff",
     "\t\tcase hopeless(err):\n\t\t\twait = f.opts.MinBackoff"),
    ("follower.go", "the backoff never grows",
     "\t\t\tif wait *= 2; wait > f.opts.MaxBackoff {", "\t\t\tif wait *= 1; wait > f.opts.MaxBackoff {"),
    ("follower.go", "the backoff never comes back down after a good connection",
     "\t\tcase time.Since(started) >= f.opts.MaxBackoff:", "\t\tcase started.IsZero():"),
    ("follower.go", "a status other than 200 is read as a stream",
     "\tif resp.StatusCode != http.StatusOK {", "\tif false {"),
    ("follower.go", "Close does not wait for the goroutine",
     "\t\tf.cancel()\n\t\t<-f.done", "\t\tf.cancel()"),
    ("follower.go", "an unfollowable address is accepted",
     '\tif base.Scheme != "http" && base.Scheme != "https" {', "\tif false {"),
    ("server.go", "closing the server leaves its streams running",
     "\ts.CloseStreams()\n\n\t// Before the writer", "\tif false {\n\t}\n\n\t// Before the writer"),
    ("server.go", "the replication route is not registered",
     '\ts.handle("GET "+replicaPath, s.streamReplica)', "\t_ = replicaPath"),
    ("errors.go", "a position that could not be read is a 500",
     "\tcase errors.Is(err, errBadPosition):", "\tcase false:"),
    ("role.go", "a replica takes writes",
     "\tleader, replica := s.following()\n\tif !replica {\n\t\treturn true\n\t}",
     "\tleader, replica := s.following()\n\tif !replica || replica {\n\t\t_ = leader\n\t\treturn true\n\t}"),
    ("role.go", "a refusal does not say where the leader is",
     "\tw.Header().Set(headerLeader, leader)", "\t_ = leader"),
    ("role.go", "following is never noticed",
     '\treturn s.role.leader, s.role.leader != ""', "\treturn s.role.leader, false"),
    ("role.go", "promote raises the term before stopping the follower",
     "\tif err := s.stopFollowing(); err != nil {\n\t\treturn 0, err\n\t}\n\treturn s.db.Promote()",
     "\tterm, err := s.db.Promote()\n\tif err != nil {\n\t\treturn 0, err\n\t}\n\tif err := s.stopFollowing(); err != nil {\n\t\treturn 0, err\n\t}\n\treturn term, nil"),
    ("role.go", "promote does not stop the follower at all",
     "\tif err := s.stopFollowing(); err != nil {\n\t\treturn 0, err\n\t}\n\treturn s.db.Promote()",
     "\treturn s.db.Promote()"),
    ("role.go", "stopFollowing forgets to clear the leader",
     '\ts.role.leader, s.role.stop = "", nil', "\ts.role.stop = nil"),
    ("role.go", "a second leader may be followed",
     "\tif s.role.stop != nil {", "\tif false {"),
    ("role.go", "the After header is ignored",
     '\traw := r.Header.Get(headerAfter)\n\tif raw == "" {\n\t\treturn true\n\t}',
     '\traw := r.Header.Get(headerAfter)\n\t_ = raw\n\tif true {\n\t\treturn true\n\t}'),
    ("role.go", "a stale read is answered instead of refused",
     "\t\tif err := s.db.Reached(pos); err != nil {", "\t\tif err := s.db.Reached(pos); false {"),
    ("role.go", "a wait does not wait",
     "\tif err := s.db.Await(pos, until); err != nil {", "\tif err := s.db.Reached(pos); err != nil {"),
    ("role.go", "the wait header is ignored and nothing waits",
     "\tif wait == 0 {", "\tif true {"),
    ("role.go", "a write hands back no position",
     "\t\tw.Header().Set(headerPosition, encoded)\n\t}", "\t\t_ = encoded\n\t}"),
    ("role.go", "status always says leader",
     '\tif replica {\n\t\tbody.Role = "replica"\n\t}', '\tif replica \u0026\u0026 !replica {\n\t\tbody.Role = "replica"\n\t}'),
    ("role.go", "a negative wait is accepted",
     "\tif wait < 0 {", "\tif false {"),
    ("keys.go", "a put does not check the role",
     '\tif !s.mayWrite(w, r) {\n\t\treturn\n\t}\n\n\tkey := []byte(r.PathValue("key"))\n\n\texpires',
     '\tkey := []byte(r.PathValue("key"))\n\n\texpires'),
    ("keys.go", "a delete does not check the role",
     "\tif !s.mayWrite(w, r) {\n\t\treturn\n\t}\n\n\tif err := s.writes.Delete(",
     "\tif err := s.writes.Delete("),
    ("keys.go", "a read ignores the After header",
     "\tif !s.notStale(w, r) {\n\t\treturn\n\t}", "\tif false {\n\t\treturn\n\t}"),
    ("batch.go", "a batch does not check the role",
     "\tif !s.mayWrite(w, r) {\n\t\treturn\n\t}\n\n\t// Refused on the declared length",
     "\t// Refused on the declared length"),
    ("scan.go", "a range ignores the After header",
     "\tif !s.notStale(w, r) {\n\t\treturn\n\t}", "\tif false {\n\t\treturn\n\t}"),
    ("server.go", "closing the server leaves the follower running",
     '\tif err := s.stopFollowing(); err != nil {\n\t\ts.log.Error("stopping the follower", "err", err)\n\t}',
     "\t{\n\t}"),
    ("ops.go", "the token check lets everything through",
     '\tif s.opts.Token == "" {\n\t\treturn true\n\t}',
     '\tif s.opts.Token == "" || s.opts.Token != "" {\n\t\treturn true\n\t}'),
    ("ops.go", "the token covers the health check too",
     "\tif r.URL.Path == healthPath {\n\t\treturn true\n\t}", "\tif false {\n\t\treturn true\n\t}"),
    ("ops.go", "every route is exempt, not just health",
     "\tif r.URL.Path == healthPath {\n\t\treturn true\n\t}",
     "\tif r.URL.Path != healthPath || true {\n\t\treturn true\n\t}"),
    ("ops.go", "a wrong token is accepted if it is a prefix",
     "\treturn subtle.ConstantTimeCompare(\n\t\t[]byte(strings.TrimPrefix(given, prefix)), []byte(s.opts.Token)) == 1",
     "\t_ = subtle.ConstantTimeCompare\n\treturn strings.HasPrefix(s.opts.Token, strings.TrimPrefix(given, prefix))"),
    ("ops.go", "nothing is counted",
     "\t\ts.metrics.observe(route, r.Method, counted.status, took)", "\t\t_ = took"),
    ("ops.go", "the status a handler sent is not remembered",
     "\tif !a.wrote {\n\t\ta.status, a.wrote = status, true\n\t}",
     "\tif !a.wrote {\n\t\ta.wrote = true\n\t}"),
    ("ops.go", "health does not ask the store anything",
     "\tif err := s.db.Reached(litekv.DBPosition{}); err != nil {",
     "\tif err := s.db.Reached(litekv.DBPosition{}); false {"),
    ("ops.go", "a bucket counts only what falls exactly in it",
     "\t\tif seconds <= at {", "\t\tif seconds == at {"),
    ("server.go", "the route label is the path rather than the pattern",
     '\troute := pattern\n\tif _, path, found := strings.Cut(pattern, " "); found {\n\t\troute = path\n\t}',
     '\troute := pattern\n\tif _, path, found := strings.Cut(pattern, " "); found {\n\t\troute = path\n\t}\n\troute = "/"'),
    ("server.go", "the token is not checked at all",
     "\tif !s.allowed(r) {\n\t\tunauthorized(w)\n\t\treturn\n\t}", "\tif false {\n\t\tunauthorized(w)\n\t\treturn\n\t}"),
    ("replica.go", "a stream keeps the server's write deadline",
     "\tif err := http.NewResponseController(w).SetWriteDeadline(time.Time{}); err != nil {",
     "\tif err := http.NewResponseController(w).SetWriteDeadline(time.Now().Add(time.Second)); err != nil {"),
    ("follower.go", "a follower does not present its token",
     '\tif f.opts.Token != "" {\n\t\treq.Header.Set("Authorization", "Bearer "+f.opts.Token)\n\t}',
     '\tif false {\n\t\treq.Header.Set("Authorization", "Bearer "+f.opts.Token)\n\t}'),
    ("replica.go", "a quiet leader never says it is there",
     "\tif beat := s.opts.heartbeat(); beat > 0 {", "\tif beat := s.opts.heartbeat(); false {"),
    ("replica.go", "a heartbeat goes out as a batch",
     "\t\t\t\t\tif err := out.frame(frameHeartbeat, s.db.Position(), nil); err != nil {",
     "\t\t\t\t\tif err := out.frame(frameBatch, s.db.Position(), nil); err != nil {"),
    ("replica.go", "a heartbeat that fails to go out is not noticed",
     "\t\t\t\t\t\tonce.Do(func() { close(broken) })", "\t\t\t\t\t\tonce.Do(func() { _ = broken })"),
    ("follower.go", "a follower waits on a silent leader for ever",
     "\tif f.opts.Idle > 0 {", "\tif false {"),
    ("follower.go", "the idle deadline moves on frames rather than on bytes",
     "\t\tbody = &alive{r: resp.Body, beat: func() { silent.Reset(f.opts.Idle) }}",
     "\t\t_ = &alive{r: resp.Body, beat: func() { silent.Reset(f.opts.Idle) }}"),
    ("follower.go", "a heartbeat is taken for a frame the follower does not know",
     "\t\tcase frameHeartbeat:", "\t\tcase 'Z':"),
    ("replica.go", "the handler does not wait for its heartbeat goroutine",
     "\tvar beating sync.WaitGroup\n\tdefer beating.Wait()", "\tvar beating sync.WaitGroup"),
    ("replica.go", "an open stream is not counted",
     "\ts.streaming.Add(1)\n\tdefer s.streaming.Add(-1)", "\ts.streaming.Add(0)"),
    ("replica.go", "a stream that ended is still counted",
     "\ts.streaming.Add(1)\n\tdefer s.streaming.Add(-1)", "\ts.streaming.Add(1)"),
    ("acks.go", "a write does not wait for anybody",
     "\t\tgot, changed := f.count(want)\n\t\tif got >= need {", "\t\tgot, changed := f.count(want)\n\t\tif true || got >= need {"),
    ("acks.go", "a follower behind the write counts as having it",
     "\treturn acked.Log.Seq >= want.Log.Seq", "\treturn true"),
    ("acks.go", "the term is not checked, so another leader's follower counts",
     "\tif acked.Term != want.Term {\n\t\treturn acked.Term > want.Term\n\t}",
     "\tif false {\n\t\treturn acked.Term > want.Term\n\t}"),
    ("acks.go", "an ack from a stranger is taken",
     "\twas, streaming := f.at[id]\n\tif !streaming {\n\t\treturn false\n\t}",
     "\twas := f.at[id]"),
    ("acks.go", "an ack out of order takes a follower backwards",
     "\tif reaches(was, at) {\n\t\treturn true // an ack that arrived out of order, which a retry can do\n\t}",
     "\t_ = was"),
    ("acks.go", "a follower that went away keeps counting",
     "\tdelete(f.at, id)\n\tf.wake()", "\tf.wake()"),
    ("acks.go", "nothing waiting is ever woken",
     "\tclose(f.changed)\n\tf.changed = make(chan struct{})",
     "\tif false {\n\t\tclose(f.changed)\n\t}\n\tf.changed = make(chan struct{})"),
    ("role.go", "a write that was not replicated still answers 204",
     "\treturn http.StatusAccepted\n}", "\treturn http.StatusNoContent\n}"),
    ("role.go", "the number of followers that had it is not reported",
     "\tw.Header().Set(headerReplicated, strconv.Itoa(got))", "\t_ = strconv.Itoa(got)"),
    ("role.go", "WaitFor unset still waits",
     "\tif need <= 0 {\n\t\treturn http.StatusNoContent\n\t}", "\tif false {\n\t\treturn http.StatusNoContent\n\t}"),
    ("replica.go", "a stream does not register its follower",
     "\ts.followers.attach(id, from)\n\tdefer s.followers.detach(id)", "\t_ = id"),
    ("follower.go", "a follower never says how far it has got",
     "\tf.latest.Store(&at)", "\t_ = at"),
    ("follower.go", "a follower does not say who it is",
     '\ttarget.RawQuery = url.Values{"from": {at}, "id": {f.id}}.Encode()',
     '\ttarget.RawQuery = url.Values{"from": {at}}.Encode()'),
    ("role.go", "a fenced store does not say so in its status",
     "\t\tFenced: s.db.Fenced(), Segments: s.db.Segments(), Keys: s.db.Len()}",
     "\t\tSegments: s.db.Segments(), Keys: s.db.Len()}"),
    ("ops.go", "the fenced gauge is always zero",
     '\t\t\tboolean(s.db.Fenced())},', "\t\t\t0},"),
    ("ops.go", "the fenced gauge is always one",
     "\tif yes {\n\t\treturn 1\n\t}\n\treturn 0", "\t_ = yes\n\treturn 1"),
    ("replica.go", "the spool file is left on the disk",
     "\tif err := os.Remove(file.Name()); err != nil {\n\t\t_ = file.Close()\n\t\treturn nil, 0, litekv.DBPosition{}, nil, err\n\t}",
     "\tif false {\n\t\t_ = file.Close()\n\t}"),
    ("replica.go", "the spool file is not rewound before it is sent",
     "\tsize, err := file.Seek(0, io.SeekEnd)\n\tif err == nil {\n\t\t_, err = file.Seek(0, io.SeekStart)\n\t}",
     "\tsize, err := file.Seek(0, io.SeekEnd)"),
    ("replica.go", "a short snapshot goes out as if it were whole",
     "\tif sent != length {", "\tif false {"),
    ("follower.go", "a snapshot is read into memory rather than streamed",
     "\t\t\tif err := f.take(next, body, length, opts); err != nil {\n\t\t\t\treturn err\n\t\t\t}",
     "\t\t\twhole, err := readPayload(body, length)\n\t\t\tif err != nil {\n\t\t\t\treturn err\n\t\t\t}\n\t\t\tif err := f.db.ApplySnapshot(next, bytes.NewReader(whole), opts); err != nil {\n\t\t\t\treturn err\n\t\t\t}"),
    ("follower.go", "what a snapshot did not read is left on the connection",
     "\tif _, err := io.Copy(io.Discard, payload); err != nil {\n\t\treturn err\n\t}\n\treturn applied",
     "\treturn applied"),
    ("follower.go", "a heartbeat may carry a payload",
     "\t\t\tif length != 0 {\n\t\t\t\treturn fmt.Errorf(\"a heartbeat carrying %d bytes\", length)\n\t\t\t}",
     "\t\t\t_ = length"),
    # --- one process owns a directory ---------------------------------------
    # Engine files, named with a leading ./ — see locate() in mutate.py. These
    # run the engine's suite, which is fifteen times the server's, so a sweep
    # that includes them is minutes rather than seconds.
    ("./lock_flock.go", "the lock is shared rather than exclusive",
     "syscall.LOCK_EX|syscall.LOCK_NB", "syscall.LOCK_SH|syscall.LOCK_NB"),
    ("./db.go", "the lock is taken after the directory has been read",
     "\tlock, err := disk.Lock(filepath.Join(dir, lockName))\n\tif err != nil {\n\t\treturn nil, err\n\t}",
     "\tif _, err := segmentIDs(dir); err != nil {\n\t\treturn nil, err\n\t}\n\tlock, err := disk.Lock(filepath.Join(dir, lockName))\n\tif err != nil {\n\t\treturn nil, err\n\t}"),
    ("./db.go", "an open that fails keeps the lock",
     "\tdb, err := openLocked(dir, opts, lock)\n\tif err != nil {\n\t\tlock.Unlock()\n\t\treturn nil, err\n\t}",
     "\tdb, err := openLocked(dir, opts, lock)\n\tif err != nil {\n\t\treturn nil, err\n\t}"),
    ("./db.go", "Close lets go of the lock before it closes the logs",
     "\terr := db.closeSegments()\n",
     "\tif uerr := db.lock.Unlock(); uerr != nil {\n\t\treturn uerr\n\t}\n\terr := db.closeSegments()\n"),
    ("./db.go", "Close never lets go of the lock",
     "\tif uerr := db.lock.Unlock(); err == nil {\n\t\terr = uerr\n\t}",
     "\t_ = db.lock"),
    # Both filters, not one. LOCK is turned away twice over — it has no .seg
    # suffix and its name is not a number — and removing either alone changes
    # nothing, which is two checks hiding each other in the way AGENTS.md
    # describes for latestOffsets. The mutation has to take both.
    ("./db.go", "the lock file is counted as a log",
     "\t\tif entry.IsDir() || !strings.HasSuffix(name, segmentSuffix) {\n\t\t\tcontinue\n\t\t}\n\t\tid, err := strconv.ParseUint(strings.TrimSuffix(name, segmentSuffix), 10, 64)\n\t\tif err != nil {\n\t\t\tcontinue // not ours\n\t\t}",
     "\t\tif entry.IsDir() {\n\t\t\tcontinue\n\t\t}\n\t\tid, _ := strconv.ParseUint(strings.TrimSuffix(name, segmentSuffix), 10, 64)"),
    # The errors.Is call is left standing and only its result widened: taking
    # the call out leaves "errors" imported and not used, which is a mutation
    # that does not build and therefore never ran. See the mutation traps in
    # AGENTS.md.
    ("./lock_flock.go", "any failure to lock is reported as somebody else holding it",
     "\treturn errors.Is(err, syscall.EWOULDBLOCK)\n",
     "\treturn errors.Is(err, syscall.EWOULDBLOCK) || true\n"),
    ("./lock_flock.go", "the lock is taken but waited for rather than refused",
     "syscall.LOCK_EX|syscall.LOCK_NB", "syscall.LOCK_EX"),
    # There is deliberately no mutation for dropping the explicit LOCK_UN from
    # Unlock. Closing the descriptor releases the lock by itself, so a version
    # without it behaves identically — an equivalent mutant, not a mutation,
    # and one that would sit in the survivor list forever implying a missing
    # test. The explicit call is there for the ordering, which
    # TestTheLockIsReleasedAfterTheLastLogIsClosed checks through the seam.
]
