"""What to break, and what to call it.

Each entry is (file under server/, what the break means, exact text, replacement).
The text is matched exactly and must appear exactly once — see the mutation traps
in AGENTS.md for every way that goes wrong quietly.
"""

MUTATIONS = [
    ("keys.go", "HEAD sends the value anyway",
     "\tif r.Method == http.MethodHead {", "\tif false {"),
    ("keys.go", "a declared oversize body is read before it is refused",
     "\tif r.ContentLength > s.opts.MaxValue {", "\tif false {"),
    ("keys.go", "the expiry header is stored as an ordinary write",
     "\tif expires.IsZero() {", "\tif true {"),
    ("keys.go", "an unparseable expiry header is ignored",
     '\t\treturn time.Time{}, badRequest("%s must be an RFC 3339 time", headerExpires)',
     "\t\treturn time.Time{}, nil"),
    ("keys.go", "no Content-Length on a value",
     '\tw.Header().Set("Content-Length", strconv.Itoa(len(value)))', "\t_ = strconv.Itoa"),
    ("keys.go", "a delete of a missing key is a 404",
     "\tw.WriteHeader(http.StatusNoContent)\n}\n\n// expiryOf",
     "\tw.WriteHeader(http.StatusNotFound)\n}\n\n// expiryOf"),
    ("errors.go", "a deleted key is not a 404",
     "\t\terrors.Is(err, litekv.ErrorKeyDeleted),\n", ""),
    ("errors.go", "an expired key is not a 404",
     "\t\terrors.Is(err, litekv.ErrorKeyExpired):", "\t\tfalse:"),
    ("errors.go", "a fenced store answers without its term",
     "\tif errors.Is(err, litekv.ErrorFenced) {", "\tif false {"),
    ("errors.go", "a 500 says nothing at all",
     '\t\tmessage = "internal error"', "\t\t_ = message"),
    ("errors.go", "a 500 tells the client what went wrong",
     '\t\tmessage = "internal error"', "\t\tmessage = err.Error()"),
    ("errors.go", "a body over the limit is a 500",
     "\tif errors.As(err, &tooBig) {", "\tif false && errors.As(err, &tooBig) {"),
    ("errors.go", "a closed store is a 500",
     "\tcase errors.Is(err, litekv.ErrorClosed):", "\tcase false:"),
    ("server.go", "MaxValue keeps whatever it was given",
     "\tif opts.MaxValue <= 0 {", "\tif false {"),
    ("server.go", "the queue is not in the write path",
     "\t\twrites:  writer,", "\t\twrites:  db,"),
    ("server.go", "Close leaves the writer running",
     "\treturn s.writer.Close()", "\treturn nil"),
    ("server.go", "the Queue option is dropped on the floor",
     "litekv.WriterOptions{Queue: opts.Queue}", "litekv.WriterOptions{}"),
    ("keys.go", "a delete goes round the queue",
     "\tif err := s.writes.Delete(", "\tif err := s.db.Delete("),
    ("keys.go", "a write goes round the queue",
     "\t\terr = s.writes.Write(key, value)", "\t\terr = s.db.Write(key, value)"),
    # --- replication over the wire -----------------------------------------
    ("replica.go", "a leader hangs up on a diverged follower instead of snapshotting",
     "\t\tif !errors.Is(err, litekv.ErrorDiverged) {", "\t\tif true {"),
    ("replica.go", "the snapshot's hold is released before Follow takes its own",
     "\t\t_, err := s.db.Follow(from, holding, send, until, litekv.ReplicaOptions{})",
     "\t\tif holding != nil {\n\t\t\tholding()\n\t\t}\n\t\t_, err := s.db.Follow(from, nil, send, until, litekv.ReplicaOptions{})"),
    ("replica.go", "a frame's claimed length is not bounded",
     "\tif most < 0 || length > uint64(most) {", "\tif false {"),
    ("replica.go", "the payload is allocated at the length claimed",
     "\tpayload := make([]byte, 0, min(length, chunk))",
     "\tpayload := make([]byte, 0, length)"),
    ("replica.go", "a short payload is taken as a whole frame",
     "\t\t\treturn 0, litekv.DBPosition{}, nil, err\n\t\t}\n\t\tpayload = payload[:len(payload)+room]",
     "\t\t\treturn header[0], at, payload, nil\n\t\t}\n\t\tpayload = payload[:len(payload)+room]"),
    ("replica.go", "the frames are not flushed as they are cut",
     "\t\tflusher.Flush()\n\t\treturn nil\n\t}", "\t\treturn nil\n\t}"),
    ("replica.go", "a snapshot frame goes out as a batch",
     "\t\t\terr := writeFrame(w, frameSnapshot, from, body.Bytes())",
     "\t\t\terr := writeFrame(w, frameBatch, from, body.Bytes())"),
    ("replica.go", "the position the batch leads to is not sent with it",
     "\t\tif err := writeFrame(w, frameBatch, next, batch); err != nil {",
     "\t\tif err := writeFrame(w, frameBatch, litekv.DBPosition{}, batch); err != nil {"),
    ("replica.go", "a from that is not a position is believed",
     "\t\treturn litekv.DBPosition{}, fmt.Errorf(\"%w: %s\", errBadPosition, err)\n\t}\n\n\tvar pos litekv.DBPosition",
     "\t\treturn litekv.DBPosition{}, nil\n\t}\n\n\tvar pos litekv.DBPosition"),
    ("replica.go", "a position is padded base64 rather than raw",
     "\treturn base64.RawURLEncoding.EncodeToString(encoded), nil",
     "\treturn base64.URLEncoding.EncodeToString(encoded), nil"),
    ("replica.go", "a stream is handed out after the streams are closed",
     "\tcase <-s.streams:\n\t\t// A server on its way down.", "\tcase <-make(chan struct{}):\n\t\t// A server on its way down."),
    ("replica.go", "the stream ignores the streams being closed",
     "\t\tcase <-s.streams:\n\t\tcase <-served:", "\t\tcase <-served:"),
    ("replica.go", "a follower carrying a newer term does not fence the leader",
     "\tif from.Term > s.db.Term() {", "\tif false {"),
    ("replica.go", "the leader hears the newer term but does not write it down",
     "\t\tif _, noted := s.db.Since(from, io.Discard, litekv.ReplicaOptions{}); noted != nil {",
     "\t\tif _, noted := error(nil), error(nil); noted != nil {"),
    ("follower.go", "a follower asks from nowhere rather than from where it is",
     "\tat, err := positionParam(f.db.Applied())", "\tat, err := positionParam(litekv.DBPosition{})"),
    ("follower.go", "a follower applies a batch from wherever the leader said",
     "\t\t\tfrom := f.db.Applied()", "\t\t\tfrom := next"),
    ("follower.go", "a snapshot is applied as a batch",
     "\t\tcase frameSnapshot:", "\t\tcase frameBatch + 1:"),
    ("follower.go", "a follower gives up when the connection ends",
     "\t\tselect {\n\t\tcase <-ctx.Done():\n\t\t\treturn\n\t\tcase <-time.After(delay):\n\t\t}",
     "\t\t_ = delay\n\t\treturn"),
    ("follower.go", "a refusal is retried as fast as an ordinary disconnection",
     "\t\tcase hopeless(err):\n\t\t\twait = f.opts.MaxBackoff",
     "\t\tcase hopeless(err):\n\t\t\twait = f.opts.MinBackoff"),
    ("follower.go", "the backoff never grows",
     "\t\t\tif wait *= 2; wait > f.opts.MaxBackoff {", "\t\t\tif wait *= 1; wait > f.opts.MaxBackoff {"),
    ("follower.go", "the backoff never comes back down after a good connection",
     "\t\tcase time.Since(started) >= f.opts.MaxBackoff:", "\t\tcase started.IsZero():"),
    ("follower.go", "a status other than 200 is read as a stream",
     "\tif resp.StatusCode != http.StatusOK {", "\tif false {"),
    ("follower.go", "Close does not wait for the goroutine",
     "\t\tf.cancel()\n\t\t<-f.done", "\t\tf.cancel()"),
    ("follower.go", "an unfollowable address is accepted",
     '\tif base.Scheme != "http" && base.Scheme != "https" {', "\tif false {"),
    ("server.go", "closing the server leaves its streams running",
     "\ts.CloseStreams()\n\n\t// Before the writer", "\tif false {\n\t}\n\n\t// Before the writer"),
    ("server.go", "the replication route is not registered",
     '\ts.mux.HandleFunc("GET "+replicaPath, s.streamReplica)', "\t_ = replicaPath"),
    ("errors.go", "a position that could not be read is a 500",
     "\tcase errors.Is(err, errBadPosition):", "\tcase false:"),
    ("role.go", "a replica takes writes",
     "\tleader, replica := s.following()\n\tif !replica {\n\t\treturn true\n\t}",
     "\tleader, replica := s.following()\n\tif !replica || replica {\n\t\t_ = leader\n\t\treturn true\n\t}"),
    ("role.go", "a refusal does not say where the leader is",
     "\tw.Header().Set(headerLeader, leader)", "\t_ = leader"),
    ("role.go", "following is never noticed",
     '\treturn s.role.leader, s.role.leader != ""', "\treturn s.role.leader, false"),
    ("role.go", "promote raises the term before stopping the follower",
     "\tif err := s.stopFollowing(); err != nil {\n\t\treturn 0, err\n\t}\n\treturn s.db.Promote()",
     "\tterm, err := s.db.Promote()\n\tif err != nil {\n\t\treturn 0, err\n\t}\n\tif err := s.stopFollowing(); err != nil {\n\t\treturn 0, err\n\t}\n\treturn term, nil"),
    ("role.go", "promote does not stop the follower at all",
     "\tif err := s.stopFollowing(); err != nil {\n\t\treturn 0, err\n\t}\n\treturn s.db.Promote()",
     "\treturn s.db.Promote()"),
    ("role.go", "stopFollowing forgets to clear the leader",
     '\ts.role.leader, s.role.stop = "", nil', "\ts.role.stop = nil"),
    ("role.go", "a second leader may be followed",
     "\tif s.role.stop != nil {", "\tif false {"),
    ("role.go", "the After header is ignored",
     '\traw := r.Header.Get(headerAfter)\n\tif raw == "" {\n\t\treturn true\n\t}',
     '\traw := r.Header.Get(headerAfter)\n\t_ = raw\n\tif true {\n\t\treturn true\n\t}'),
    ("role.go", "a stale read is answered instead of refused",
     "\t\tif err := s.db.Reached(pos); err != nil {", "\t\tif err := s.db.Reached(pos); false {"),
    ("role.go", "a wait does not wait",
     "\tif err := s.db.Await(pos, until); err != nil {", "\tif err := s.db.Reached(pos); err != nil {"),
    ("role.go", "the wait header is ignored and nothing waits",
     "\tif wait == 0 {", "\tif true {"),
    ("role.go", "a write hands back no position",
     "\t\tw.Header().Set(headerPosition, at)\n\t}\n}", "\t\t_ = at\n\t}\n}"),
    ("role.go", "status always says leader",
     '\tif replica {\n\t\tbody.Role = "replica"\n\t}', '\tif replica \u0026\u0026 !replica {\n\t\tbody.Role = "replica"\n\t}'),
    ("role.go", "a negative wait is accepted",
     "\tif wait < 0 {", "\tif false {"),
    ("keys.go", "a put does not check the role",
     '\tif !s.mayWrite(w, r) {\n\t\treturn\n\t}\n\n\tkey := []byte(r.PathValue("key"))\n\n\texpires',
     '\tkey := []byte(r.PathValue("key"))\n\n\texpires'),
    ("keys.go", "a delete does not check the role",
     "\tif !s.mayWrite(w, r) {\n\t\treturn\n\t}\n\n\tif err := s.writes.Delete(",
     "\tif err := s.writes.Delete("),
    ("keys.go", "a read ignores the After header",
     "\tif !s.notStale(w, r) {\n\t\treturn\n\t}", "\tif false {\n\t\treturn\n\t}"),
    ("batch.go", "a batch does not check the role",
     "\tif !s.mayWrite(w, r) {\n\t\treturn\n\t}\n\n\t// Refused on the declared length",
     "\t// Refused on the declared length"),
    ("scan.go", "a range ignores the After header",
     "\tif !s.notStale(w, r) {\n\t\treturn\n\t}", "\tif false {\n\t\treturn\n\t}"),
    ("server.go", "closing the server leaves the follower running",
     '\tif err := s.stopFollowing(); err != nil {\n\t\ts.log.Error("stopping the follower", "err", err)\n\t}',
     "\t{\n\t}"),
]
